# -*- coding: utf-8 -*-
"""Kmeans.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iDLw5CHDdITRYzFbrZDa56bW7hDoJB8M
"""

import pandas as pd

data = pd.read_excel('Movie_Gross_Value.xlsx')

data

k = 6

X = data[['RATING', 'Gross','VOTES']]

from sklearn.cluster import KMeans

kmeans = KMeans(k)

kmeans.fit(X)

allLabel = kmeans.labels_

data['Cluster'] = allLabel

import matplotlib.pyplot as plt

from mpl_toolkits.mplot3d import Axes3D

VisualizeAll = plt.figure()
VAll = VisualizeAll.add_subplot(111, projection='3d')
scatter = VAll.scatter(data['RATING'], data['Gross'], data['VOTES'], c=allLabel, cmap='rainbow')
VAll.set_xlabel('RATING')
VAll.set_ylabel('Gross')
VAll.set_zlabel('VOTES')
VAll.set_title('K-means Clustering')
title = VAll.legend(*scatter.legend_elements(), title="Clusters")
VAll.add_artist(title)

plt.scatter(data['RATING'], data['Gross'], c=allLabel, cmap='rainbow')
plt.xlabel('Rating')
plt.ylabel('Gross')
plt.title('K-means Clustering Rating vs Gross')
plt.show()

plt.scatter(data['Gross'], data['VOTES'], c=allLabel, cmap='rainbow')
plt.xlabel('Gross')
plt.ylabel('VOTES')
plt.title('K-means Clustering VOTES vs Gross')
plt.show()

plt.scatter(data['VOTES'], data['RATING'], c=allLabel, cmap='rainbow')
plt.xlabel('VOTES')
plt.ylabel('RATING')
plt.title('K-means Clustering VOTES vs RATING')
plt.show()